name: Generate book
permissions:
  contents: read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install certifi mdformat requests tkinter xmltodict
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends pandoc texlive-latex-base
    - name: makeBook
      run: |
        python3 utilities/makeBook.py .
        cat makeBook.log
    - name: indexBook
      run: |
        python3 utilities/indexBook.py .
        cat indexBook.log
    - name: RFCbib6
      run: |
        python3 utilities/RFCbib6.py .
        cat RFCbib6.log
    - name: bakeBook
      run: |
        python3 utilities/bakeBook.py .
        cat bakeBook.log
    - name: check epub for errors
      run: |
        epubcheck pdf/baked.epub
